# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('quantity', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0448\u0442.')),
                ('price', models.CharField(max_length=50, verbose_name='\u0414\u0438\u0430\u043f\u043e\u0437\u043e\u043d \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('icon', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='mysite.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
