# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20160529_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_temporary',
            field=models.BooleanField(verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043a\u043e\u0440\u0437\u0438\u043d\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
