# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
