# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='mysite.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
